spring:
  profiles:
    include: common
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /home/dev_web/smartixBatch/upload
      enabled: true
  rabbitmq:
    host: 192.168.21.10
    port: 5672
    username: admin
    password: smartix0419
  activemq:
    broker-url: tcp://192.168.51.10:61616
    user: admin  # ActiveMQ 사용자명
    password: admin  # ActiveMQ 비밀번호
    in-memory: false  # 인메모리 모드 비활성화
    pool:
      enabled: true  # 커넥션 풀 활성화
      max-connections: 10  # 최대 연결 수