spring:
  profiles:
    include: common
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /home/dev_web/smartixBatch/upload
      enabled: true
