spring:
  profiles:
    include: common
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /home/dev_web/smartixBatch/upload
      enabled: true
  rabbitmq:
    host: 192.168.21.10
    port: 5672
    username: admin
    password: smartix0419
  artemis:
    broker-url: tcp://192.168.21.10:61616
    user: admin  # ActiveMQ 사용자명
    password: "smartix!0419"  # ActiveMQ 비밀번호
  jms:
    pub-sub-domain: true