spring:
  profiles:
    include: common
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /home/dev_web/smartixBatch/upload
      enabled: true
  rabbitmq:
    host: 192.168.21.10
    port: 5672
    username: admin
    password: smartix0419
  artemis:
    broker-url: tcp://192.168.21.10:61616
    user: admin  # ActiveMQ 사용자명
    password: "smartix!0419"  # ActiveMQ 비밀번호
  jms:
    pub-sub-domain: true

  # 스프링 캐시를 Redis로 사용
  cache:
    type: redis
    redis:
      # 기본 TTL (ms). @Cacheable TTL을 코드로 지정하지 않을 때 사용
      time-to-live: 600s       # 10분
      use-key-prefix: true
      # key-prefix: ""           # 필요 시 프리픽스 강제 지정

logging:
  level:
    org.springframework.data.redis: ERROR
    org.springframework.cache: ERROR