server:
  port: 8080
  tomcat:
    threads:
      max: 500 # 상태 API QPS 대응
    accept-count: 2000
    max-connections: 10000
  
settings:
  jwt:
    secret: smartixAccessCredential0419jH8lURsecX0r7NSePoGxUUBgu10W8v4PL6Lucda1X7M=
  allowedOrigins:
    - http://localhost:8080
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:8081
  
spring:  
  datasource:    
    hSql:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      url: jdbc:hsqldb:mem:testdb # D:\programming\hsqldb-2.7.3\hsqldb\lib>java -cp hsqldb.jar org.hsqldb.util.DatabaseManagerSwing --url jdbc:hsqldb:mem:testdb --user sa --password "1234"
      username: sa
      password: 1234

queue:
  system:
    windowMinutes: 3
    maxEtaMinutes: 180
    token:
      secretKey: MO6c+g04gJeWYzeZTTTT1eEN7jo06sR18BhsiyRNrYg=
      validityMillis: 180000
    waitSession:
      validitySecond: 90
    eventIds:
      - GD2501794
#      - GD2502001
#      - GD2503005
    initialAllowLimit:
      GD2501794: 1
#      GD2502001: 1
#      GD2503005: 1
